# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XBz9eLuQVtlBkeTM3NUlBdu9yWV0sFyT
"""

def dars_jadvali(fan):
  if fan=="Sun'iy intellekt":
    return "Siz 213-xonaga kiring"
  elif fan=="Elektronika va sxemalar":
    return "Tabiiy fanlar kafedrasiga murojaat qiling"
  elif alomat=="Kompyuterni tashkil etish":
    return "Bu darsga kech qoldingiz"
  elif alomat=="Ma'lumotlar tuzilmasi va algoritmlar":
    return "316-xonaga kiring"
  elif alomat=="Kiberxavfsizlik asoslari":
    return "329-xonaga kiring"
  else:
    return "11.11.2024 sanada bunday dars mavjud emas!"

fan= input("Fan nomini kiriting: ")
natija=dars_jadvali(fan)
print(natija)

def apteka(dori):
  if dori=="Boshim og'riyapti":
    return "Siz paratsetamol ichishingiz kerak"
  elif dori=="Tishim og'riyapti":
    return "Siz Bolnol ichishingiz kerak"
  elif dori=="Qornim og'riyapti":
    return "Siz kyupen ichishingiz kerak"
  elif dori=="Oshqozonimda yara bor":
    return "Shifokorga murojaat qiling"
  elif dori=="Ko'nglim ayniyapti":
    return "АЦЦ tabletkasini iching"
  else:
    return "Bizda bu kasallikka dori mavjud emas"

dori= input("Kasallik nomini kiriting: ")
natija=apteka(dori)
print(natija)